### PR TITLE
Add haha.glb sample

### PR DESCRIPTION
**Pull request by donmccurdy**
Adds a `haha.glb` sample, and `haha.blend` source file. It should be possible to recreate both the `.glb` and `.usdz` assets (or other formats) from the `.blend` if future changes are needed. There's some color difference visible in the screenshots, but much less than the difference between Quick Look and Xcode for the same .usdz file; I believe that just comes down to default scene lighting in each application.

| USDZ (Quick Look) | glTF (https://gltf.report) |
|---|---|
| usdz_screenshot | gltf_screenshot |

Context: https://github.com/WebKit/explainers/issues/64#issuecomment-910690445

### CODE REVIEW

**Comment by grorg** [comment]
Oops! Sorry I didn't see this earlier. This is fantastic.

**Comment by grorg** [comment]
Arrgh. I pushed my version before seeing this. I'll merge it in.

**Comment by grorg** [comment]
> There's some color difference visible in the screenshots, but much less than the difference between Quick Look and Xcode for the same .usdz file; I believe that just comes down to default scene lighting in each application.

That's right. Those two have different renderers as well as use different default lighting.

**Comment by grorg** [comment]
Merged your glb and usdz files in. Thanks again.

**Comment by donmccurdy** [comment]
Thanks @grorg!

**Pull request closed without merging**
